language: rust
sudo: false
os:
- linux
rust:
  # Skip nightly for now, we have some issues to work out.
  #  - nightly
  - beta
  - stable
script:
  - cargo check --verbose --all
   # work around an issue with docmatic
  - rm -f target debug/deps/libminidump*
  - cargo test --all --verbose
  - cargo doc --verbose
after_success: sh scripts/travis-doc-upload.sh
