language: rust
sudo: false
os:
- linux
rust:
  - nightly
  - beta
  - stable
script:
  - cargo build --verbose
  - cargo test --all --verbose
  - cargo doc --verbose
after_success: sh scripts/travis-doc-upload.sh
