[package]
name = "minidump"
description = "A parser for the minidump format."
version = "0.2.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
documentation = "https://luser.github.io/rust-project-docs/minidump/minidump/"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"
keywords = ["breakpad", "symbols"]
categories = ["parsing"]
readme = "README.md"
exclude = [
    "scripts/*",
    "testdata/*",
]


[dependencies]
failure = "0.1.1"
range-map = "0.1.5"
libc = "0.2.34"
minidump-common = { version = "0.2.0", path = "minidump-common" }
encoding = "0.2"
chrono = "0.4.6"
scroll = "0.9.0"
memmap = "0.6.2"

[dev-dependencies]
test-assembler = "0.1.5"
docmatic = "0.1.2"

[workspace]
members = [
        "breakpad-symbols",
        "minidump-processor",
        "minidump-tools",
]

[replace]
"scroll:0.9.0" = { path = "../scroll" }
"scroll_derive:0.9.4" = { path = "../scroll_derive" }
