[package]
name = "minidump"
description = "A parser for the minidump format."
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
documentation = "https://luser.github.io/rust-project-docs/minidump/minidump/"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"
exclude = [
    "scripts/*",
]


[dependencies]
range-map = "0.1.5"
breakpad-symbols = { path = "breakpad-symbols" }
libc = "0.1.*"
encoding = "0.2"
chrono = "0.2.16"


[dev-dependencies]
test-assembler = "0.1.5"

[workspace]
