[workspace]
members = [
        "breakpad-symbols",
        "minidump",
        "minidump-common",
        "minidump-processor",
        "minidump-stackwalk",
        "minidump-synth",
        "minidump-unwind",
]
exclude = [
    "testdata/*",
]

[workspace.metadata.release]
shared-version = true
consolidate-commits = true
tag-name = "v{{version}}"
