[package]
name = "minidump-processor"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]

[dependencies]
breakpad-symbols = { version = "0.1.1", path = "../breakpad-symbols" }
chrono = "0.2.16"
minidump = { version = "0.1.0", path = ".." }

[dev-dependencies]
test-assembler = "0.1.5"
