[package]
name = "breakpad-symbols"
description = "A library for working with Google Breakpad's text-format symbol files."
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
documentation = "https://luser.github.io/rust-project-docs/minidump/breakpad_symbols/"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"
workspace = ".."

[dependencies]
range-map = { path = "../range-map" }
nom = "~1.2.2"
# This is technically test-dependencies, but cargo can't handle that
# when running `cargo test -p breakpad-symbols` from the repository root.
tempdir = "0.3"
